  version: '3.8'

  services:
    spring-app:
      build: .
      image: java-spring:v1
      container_name: spring-app
      restart: always
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/chat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 123456
      ports:
        - "8080:8080"
