server:
  port: 8080  # Cổng của server sẽ chạy
  servlet:
    context-path: /  # Đường dẫn gốc của ứng dụng, khi truy cập sẽ là http://localhost:8080/chat

spring:
  devtools:
    restart:
      enabled: true  # Kích hoạt tính năng tự động tải lại ứng dụng khi có thay đổi mã nguồn
  datasource:
    url: jdbc:mysql://localhost:3306/chat  # Địa chỉ cơ sở dữ liệu MySQL
    username: root  # Tên người dùng cơ sở dữ liệu
    password: 123456  # Mật khẩu của người dùng cơ sở dữ liệu
    driver-class-name: com.mysql.cj.jdbc.Driver  # Lớp trình điều khiển MySQL JDBC

  jpa:
    hibernate:
      ddl-auto: update  # Tùy chọn để Hibernate tự động cập nhật cơ sở dữ liệu
      dialect: org.hibernate.dialect.MySQL5Dialect  # Đặc tả dialect của MySQL5 cho Hibernate
    show-sql: false  # Hiển thị các câu lệnh SQL trong log khi chạy ứng dụng

jwt:
  secret: 2lElmgv+oA56bO77O0poqnbrqJAEq4qV6O55yIMhUUg=
  expiration: 900000  # 15 phút



